### ISSUE TITLE
web: wormhole links and QR codes

### ISSUE THREAD

**Issue by saljam** [saljam/cpace-machine#10]
Currently you have to go to the web UI and explicitly either create or join a wormhole. We can change that so:

- If we have a code in the fragment identifier (the hash part in the URL) we automatically join that wormhole
- If we don't have a fragment identifier we automatically create a new wormhole, saving the user a click. The user should still be able to override this and join a different wormhole.

We can also display a QR code to make it easier to send something from a phone.

Is this more confusing or less confusing than the current approach? Should we be worried about stale links with bad fragments laying around?

**Comment by FiloSottile** [comment]
It would also be cool to print a link in the CLI for the web UI.

**Comment by saljam** [comment]
re my dangling links concern, @tyehle suggests we attach an extra bit of information in the link url that tells the client if it's expired. i like that thought, since if people are going to be using the links they'll probably copy and paste them.

**Comment by saljam** [comment]
Done.
```
$ cpace-machine send foo.txt
0-waffle-certify
█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ ██▀▄██▀  █▀█ ▄█ ▄▄▄▄▄ ████
████ █   █ █▄▀█▄▀█████ ▄██ █   █ ████
████ █▄▄▄█ ██▄▀▀    ██   █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █▄▀▄▀ █ ▀▄▀ █▄▄▄▄▄▄▄████
████▄▄ ▀▄▄▄ ▄▀█▀  ██ ▄▄█   ██▀▄█▀████
████▄  ███▄▄▄▀ ▄   █  ██ ▄▄ ██▄ ▄████
████▀▄▄▀██▄█ █  █ ██ ▄█▄ ▀ ██ █▄ ████
█████▀█▀▄█▄▀▀▄█▀█▀▀▀█▀ ▀█▄█ ▄ █ ▄████
█████▀ █▄▀▄█▀█ ▀  ▀█ ▄█▄   ██ ▀▄ ████
████▄▀█▄▀█▄██ ▀▄  ▄█▀ ▀▀▄▄█▀▄▀█ ▄████
████▄█████▄▄ ▄▀ ▄ ▀█▀▄▄  ▄▄▄ █▀▀▀████
████ ▄▄▄▄▄ █ ▄ ▀█▀█▀▀ ▀▄ █▄█  █▄▄████
████ █   █ █▄  ▄▀▄█▄▄ ▄█ ▄▄▄ █▀ ▀████
████ █▄▄▄█ █   █ ▀ ▀▄  ▀ ▀█▄ ▄█▀▄████
████▄▄▄▄▄▄▄█▄█▄█▄▄███▄▄▄▄▄▄█▄██▄▄████
█████████████████████████████████████
█████████████████████████████████████
https://cpace-machine.0f.io/#0-waffle-certify
```
Can probably put the QR code and the URL behind a flag or something but this'll do for now.

We can embed expiry in URLs if dangling URLs become a problem. I'll make "automatically create a new wormhole on page load" a new issue since that involves rethinking the current web UX.
