### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by saljam** [saljam/cpace-machine#15]
the current web interface is a little too calm and bright. obviously we need dark mode css.

can we add a dark mode for the command line tool too?

**Comment by tyehle** [comment]
Everyone knows the equivalent of dark mode on the command line is ansi
colors.

**Comment by Dorson** [comment]
Recently, I coded the Dark Mode in CSS and basic Java Script.

In my version of the dark mode switch one can set multiple color themes in one CSS file and call or remember them with a short JS function.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:
